# Generated by Django 5.1.1 on 2024-09-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='amout',
            new_name='amount',
        ),
    ]
